name: generate-report

on:
  pull_request:
    branches:
      - master

jobs:
  generate-report:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2

      - name: generate report
        run: |
          go run . --token=${{ secrets.PAT }}
